apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: statistics-dashboard-ui-ingress-production
spec:
  ingressClassName: public-iks-k8s-nginx
  tls:
    - hosts:
        - metis-statistics-ui-production.eanadev.org
      secretName: eanadev.org
    - hosts:
        - metis-statistics.europeana.eu
      secretName: europeana.eu
  rules:
    - host: metis-statistics-ui-production.eanadev.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: statistics-dashboard-ui-service-production
                port:
                  number: 8080
    - host: metis-statistics.europeana.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: statistics-dashboard-ui-service-production
                port:
                  number: 8080
