apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: statistics-dashboard-ui-hpa-acceptance
spec:
  maxReplicas: MAX_REPLICAS
  minReplicas: MIN_REPLICAS
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: statistics-dashboard-ui-deployment-acceptance
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: UTILISATION_AVERAGE_PERCENT
