name: Build / Deployment
run-name: ${{ github.actor }} is ${{ github.event.inputs.run_build == 'true' && 'building and deploying' || 'deploying' }} ${{ github.event.inputs.tag_name }} to ${{ github.event.inputs.deploy_environment }}
on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'target environment'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - acceptance
        - production
      tag_name:
        description: 'tag (defaults to PROJECT_VERSION)'
        type: string
      run_build:
        description: '(re)build docker image'
        default: false
        type: boolean
jobs:
  make-env-file:
    uses: ./.github/workflows/env-file-generation.yaml
    with:
      deploy_environment: ${{ github.event.inputs.deploy_environment }}
    secrets: inherit

  run-tests:
    if: ${{ github.event.inputs.run_build == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        #with:
        #  repository: europeana/statistics-dashboard
        #  ref: feat/MET-5843-GitHub-Actions-Deployment
      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
      - run: npm install
      - run: npm run test:dev
      - run: cp coverage/**/lcov.info .
      - uses: actions/upload-artifact@master
        with:
          name: appSource
          path: src/app
      - uses: actions/upload-artifact@master
        with:
          name: appLcov
          path: ./lcov.info

  run-sonar:
    if: ${{ github.event.inputs.run_build == 'true' }}
    needs: [build-docker-image, run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Get Project Source
        uses: actions/download-artifact@master
        with:
          name: appSource
          path: src/app
      - name: Get Project LCOV
        uses: actions/download-artifact@master
        with:
          name: appLcov
          path: ./lcov.info
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=europeana
            -Dsonar.projectKey=europeana_statistics-dashboard
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.sources=src/app
            -Dsonar.exclusions=src/**/_mocked/**
            -Dsonar.javascript.lcov.reportPaths=./lcov.info/lcov.info

  build-docker-image:
    if: ${{ github.event.inputs.run_build == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        #with:
        #  repository: europeana/statistics-dashboard
      - name: Build Artifact
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
      - run: npm install
      - run: npm run dist-localised
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Extract Metadata for Docker Image
        id: meta
        uses: docker/metadata-action@v5
        env:
          PROJECT_VERSION: ${{ secrets.PROJECT_VERSION }}
        with:
          images: ${{ GITHUB_REPOSITORY }}
          #images: europeana/statistics-dashboard
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            europeana/statistics-dashboard-ui:${{ env.PROJECT_VERSION }}
            ${{ github.event.inputs.tag_name }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  call-deploy-image:
    if: always() && !contains(needs.*.result, 'failure')
    needs: [run-sonar, make-env-file]
    uses: ./.github/workflows/deploy-image.yaml
    secrets: inherit
