name: '- helper (unit testing)'
on:
  workflow_call:
    inputs:
      tag_name:
        description: 'Branch or tag to test'
        required: false
        type: string
        default: 'develop'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.tag_name || github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v5
        with:
          node-version: '22.12'
          cache: 'npm'

      - run: npm install # Bypasses the lockfile sync errors

      - run: |
          npm run test:dev

      - name: Upload LCOV Coverage
        uses: actions/upload-artifact@v4
        with:
          name: appLcov
          path: coverage/lcov.info
