name: '- helper (lint)'
on: workflow_call
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name || github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'
      - run: npm install
      - run: |
          npm run lint:ci
