name: '- helper (e2e testing)'
on:
  workflow_call:
    inputs:
      tag_name:
        description: 'Branch or tag to test'
        required: false
        type: string
        default: 'develop'

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.tag_name }}

      - uses: actions/setup-node@v5
        with:
          node-version: '22.12'
          cache: 'npm'

      - run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:ci-data
          wait-on: 'http://localhost:3001'
          wait-on-timeout: 60
          command: npm run cypress:ci

  a11y:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.tag_name }}

      - uses: actions/setup-node@v5
        with:
          node-version: '22.12'
          cache: 'npm'

      - run: npm install

      - name: Run Cypress Accessibility Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:ci-data
          wait-on: 'http://localhost:3001'
          wait-on-timeout: 60
          command: npm run cypress:ci-accessibility
